"""PyScript entry point — installs the wheels, builds the UI, mounts the runtime.

Generated by nicegui-pyodide-build; edit ``app.py`` to change the UI, not this file.
"""
import micropip  # type: ignore
from js import window  # type: ignore

window.console.log('Python: installing nicegui + nicegui_pyodide…')
# deps=False: nicegui's server deps (fastapi/uvicorn/…) don't exist in Pyodide and
# are replaced by nicegui_pyodide's import shims.
await micropip.install('{{NICEGUI_WHEEL}}', deps=False)   # type: ignore  # noqa: F704, PLE1142
await micropip.install('{{PYODIDE_WHEEL}}', deps=False)   # type: ignore  # noqa: F704, PLE1142
# tinycss2 (+ its dep webencodings) is imported eagerly by nicegui.vbuild during
# `import nicegui`; the others back markdown/rst rendering. All are pure-Python.
# Names resolve against PyPI; a --self-hosted build substitutes local wheel paths.
await micropip.install({{PYPI_INSTALL_ARGS}})  # type: ignore  # noqa: F704, PLE1142
window.console.log('Python: packages installed')

# app.py imports nicegui_pyodide FIRST (installs the shims), then builds the UI.
from app import client  # noqa: E402, I001
from nicegui_pyodide import PyodideRuntime  # noqa: E402

loading = window.document.getElementById('loading')
if loading:
    loading.style.display = 'none'

runtime = PyodideRuntime(client)
try:
    await runtime.mount()  # type: ignore  # noqa: F704, PLE1142
    window.console.log('Python: mount() complete')
except Exception as e:  # noqa: BLE001
    window.console.log(f'Python: mount() error: {e}')
    raise

window.__pyodide_ready = True  # type: ignore
window.console.log('Python: ready')
